name: salt_n_pepa
description: One-way anonymization using UUID
version: 1.0.0
repository: https://github.com/miechoo/salt-n-pepa

environment:
  sdk: ^3.5.2

dependencies:
  uuid: ^4.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
